# --- ENCODERS (Rodinhas) ---
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# --- DESATIVA TUDO QUE CAUSA RUÍDO ---
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_WS2812_STRIP=n
CONFIG_ZMK_EXT_POWER=n

# --- CORREÇÃO PARA "D" TRAVADO (DEBOUNCE ALTO) ---
# Isso ajuda muito em chips clones
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=20
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=20

# --- PREVENÇÃO DE TRAVAMENTO ---
CONFIG_EC11=n
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=n

# --- BLUETOOTH ---
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
