# --- DISPLAY OLED ---
# Ativa o OLED (se quiser desligar para testar, mude para n)
CONFIG_ZMK_DISPLAY=y

# --- ENCODERS (Rodinhas) ---
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# --- RGB (DESATIVADO) ---
# Isso garante que não haja energia indo para os pinos de LED
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_WS2812_STRIP=n

# --- SISTEMA ---
# Aumenta o debounce para evitar duplicidade de teclas no Tenstar/Clone
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=10
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# Melhora a conexão Bluetooth
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
