# --- Construção da Metade ESQUERDA ---
      - name: West Build (Sofle Left)
        run: |
          west build -s zmk/app -b nice_nano_v2 -- \
          -DSHIELD=sofle_left \
          -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" \
          -DEXTRA_SOURCES="${GITHUB_WORKSPACE}/config/widgets" \
          -DZMK_EXTRA_KCONFIG_DIRS="${GITHUB_WORKSPACE}/config/widgets" # <--- ADICIONE ESTA LINHA
          # -DSNIPPET="studio-rpc-usb-uart"

      # --- Construção da Metade DIREITA ---
      - name: West Build (Sofle Right)
        run: |
          west build --pristine -s zmk/app -b nice_nano_v2 -- \
          -DSHIELD=sofle_right \
          -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" \
          -DEXTRA_SOURCES="${GITHUB_WORKSPACE}/config/widgets" \
          -DZMK_EXTRA_KCONFIG_DIRS="${GITHUB_WORKSPACE}/config/widgets" # <--- ADICIONE ESTA LINHA
          # -DSNIPPET="studio-rpc-usb-uart"
