# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  - board: nice_nano_v2
    shield: sofle_left
    # ADICIONE ESTAS DUAS LINHAS PARA O SNIPPET DO ZMK STUDIO
    snippet: studio-rpc-usb-uart
    # ADICIONE A OPÇÃO EXTRA_KCONFIG_SOURCES AQUI:
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DEXTRA_KCONFIG_SOURCES=../config/Kconfig
  - board: nice_nano_v2
    shield: sofle_right
    # ADICIONE ESTAS DUAS LINHAS TAMBÉM PARA O LADO DIREITO
    snippet: studio-rpc-usb-uart
    # Opcional: Adicione também para o lado direito se precisar das mesmas configurações de log/display
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DEXTRA_KCONFIG_SOURCES=../config/Kconfig
