# Definicoes adicionais de Kconfig para o seu layout Sofle,
# para garantir que os simbolos sejam definidos cedo no processo de build.

CONFIG_ZMK_DISPLAY_STATUS=y
CONFIG_ZMK_ACTIVITY=y

# Níveis de log como números para prj.conf
CONFIG_ZMK_LOG_LEVEL=4 # Depuração (DBG)
CONFIG_ZMK_DISPLAY_LOG_LEVEL=4 # Depuração para o display
CONFIG_ZMK_ACTIVITY_LOG_LEVEL=4 # Depuração para a atividade

# Se CONFIG_DISPLAY_BUFFER_SIZE também for um problema, descomente e adicione aqui:
# CONFIG_DISPLAY_BUFFER_SIZE=512
