manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com
    - name: carriejv
      url-base: https://github.com
  projects:
    - name: zmk
      remote: carriejv
      revision: display-rework
      import: app/west.yml
