manifest:
  remotes:
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: urob
      revision: principal-3.5  # ou outro branch válido
      import: app/west.yml
  self:
    path: config
