manifest:
  remotes:
    - name: end3r
      url-base: https://github.com/end3r
  projects:
    - name: zmk
      remote: end3r
      revision: display-widget-support
      import: app/west.yml
  self:
    path: config

